[package]
name = "library"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.5", features = ["runtime-tokio", "sqlite", "macros"] }
dotenv = "0.15.0"
encoding_rs = "0.8.35"
regex = "1.11.1"
tokio = { version = "1.44.2", features = ["full"] }
chrono = "0.4.40"
